###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
# Emulador de terminal

$terminal = kitty

# Explorador de archivos

$fileManager = nautilus

# Menu

$menu = hyprlauncher

# Boton principal Win / Comand / super
$mainMod = SUPER 