# Prueba de audio
yay -S pipewire-audio --noconfirm
yay -S pipewire-alsa --noconfirm
yay -S alsa-lib --noconfirm
yay -S sof-firmware --noconfirm
yay -S linux-firmware-cirrus --noconfirm
yay -S alsa-firmware --noconfirm
yay -S alsa-utils --noconfirm
yay -S xdg-desktop-portal --noconfirm
yay -S xdg-desktop-portal-hyprland --noconfirm