#Archivo de configuracion hyprland
#

#Para modularizar la configuracion se ocupa
# source = [path]/+.conf


source = ./hyprland_modules/monitors.conf
source = ./hyprland_modules/variables.conf
source = ./hyprland_modules/autostart.conf
source = ./hyprland_modules/binds.conf
source = ./hyprland_modules/inputs.conf